[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"        # run Next.js dev server
  targetPort = 3000               # Next dev server port
  port = 8888                     # Netlify proxy port
  autoLaunch = false
  framework = "next"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

